### PR TITLE
Add status for ifttt.

### PR DESCRIPTION
**Pull request by alanpeabody**

### CODE REVIEW

**Comment by alanpeabody** [comment]
@jayzes didn't bother with tests for this one. Should we check DB or anything here or just assume if request works we are GTG?

**Comment by jayzes** [comment]
It's probably worth throwing in a simple request spec just since their API contract tester fails without it present. I don't feel strongly like we need to test the DB or anything in the endpoint - seems like if the app is up then we're good (enough) to go.

**Comment by alanpeabody** [comment]
@jayzes basic spec added.

**Comment by jayzes** [comment]
:boom: 

:shipit:

**Pull request merged**
